version: '3.8'

services:
  web-ui:
    # Use the image we built in Step 1
    image: nginx-web-ui:latest
    container_name: nginx-web-ui-110
    restart: unless-stopped
    networks:
      vlan110_net:
        # Assign the static IP that Tony wants
        ipv4_address: 192.168.110.225

# Declare the network
networks:
  vlan110_net:
    # Tell compose that this network was created externally
    external: true
    # The name of the network created in Step 3
    name: VLAN110
