apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IudG9ueXRlY2hsYWIuY29tIjp7InVzZXJuYW1lIjoidG9ueSIsInBhc3N3b3JkIjoiVG9ueXRlY2hsYWJAMjAyNSIsImVtYWlsIjoidG9ueUB0b255dGVjaGxhYi5jb20iLCJhdXRoIjoiZEc5dWVUcFViMjU1ZEdWamFHeGhZa0F5TURJMSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2025-11-21T15:06:55Z"
  name: harbor-registry-login
  namespace: default
  resourceVersion: "4643430"
  uid: af9a2a41-92ae-4fe7-bacf-fc671e14864b
type: kubernetes.io/dockerconfigjson